apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shortener
  labels:
    app.kubernetes.io/name: shortener
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shortener
