version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directories: ['/', '/tools']
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories: ['/deploy/postgres', '/deploy/keycloak']
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directories: ['/', '/deploy/stack/overlays', '/deploy/stack/local']
    schedule:
      interval: weekly
