#!/bin/sh
# Makes the keys, realm and passwords of a local development setup. Starts the DevSetup tool, which says what it writes.
#
#   deploy/keycloak/dev-setup [--yes] [--force] [--show]
set -eu
exec "$(dirname "$0")/../../tools/run" DevSetup "$@"
