spring:
  application:
    name: shortener
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  lifecycle:
    timeout-per-shutdown-phase: 20s
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: shortener-api
          issuer-uri: http://localhost:8180/realms/shortener
          jwk-set-uri: http://localhost:8180/realms/shortener/protocol/openid-connect/certs
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 200
        one-indexed-parameters: false
      sort:
        sort-parameter: sort
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000

server:
  shutdown: graceful
  forward-headers-strategy: native

shortener:
  shortlink:
    scopes:
      create: shortlinks:create
      claim: shortlinks:claim
      read: shortlinks:read
      delete: shortlinks:delete
      admin: shortlinks:admin

management:
  server:
    port: 8081
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 5ms,10ms,25ms,50ms,100ms,250ms,500ms,1s
