spring:
  application:
    name: shortener
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

management:
  server:
    port: 8081
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
