apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortener
  labels:
    app.kubernetes.io/name: shortener
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 16k
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [short.example.com]
      secretName: shortener-tls
  rules:
    - host: short.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shortener
                port:
                  name: http
