package uy.ct.shortener

import com.tngtech.archunit.core.importer.ClassFileImporter
import com.tngtech.archunit.core.importer.ImportOption
import com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses
import org.junit.jupiter.api.Test
import uy.ct.shortener.shortlink.ShortLinkRepository
import uy.ct.shortener.shortlink.internal.DefaultShortLinkService

/**
 * Layering rules inside the `shortlink` module, which Modulith does not check: the public API
 * never depends on `internal`, on any persistence technology or on the security framework, the
 * web adapter only talks to the service contract, and nothing depends on the web or persistence
 * adapters. Classes generated by Spring AOT are ignored.
 */
class ShortLinkArchitectureTest {

    private val classes = ClassFileImporter()
        .withImportOption(ImportOption.DoNotIncludeTests())
        .withImportOption { !it.contains("/aot") }
        .importPackages("uy.ct.shortener")

    @Test
    fun `public api does not depend on internal`() {
        noClasses().that().resideInAPackage("uy.ct.shortener.shortlink")
            .should().dependOnClassesThat().resideInAPackage("..shortlink.internal..")
            .check(classes)
    }

    @Test
    fun `web adapter uses the service contract, not the repository or its implementation`() {
        noClasses().that().resideInAPackage("..internal.web..")
            .should().dependOnClassesThat().areAssignableTo(ShortLinkRepository::class.java)
            .orShould().dependOnClassesThat().areAssignableTo(DefaultShortLinkService::class.java)
            .check(classes)
    }

    @Test
    fun `nothing depends on the web adapter`() {
        noClasses().that().resideOutsideOfPackage("..internal.web..")
            .should().dependOnClassesThat().resideInAPackage("..internal.web..")
            .check(classes)
    }

    @Test
    fun `public api is free of persistence technology`() {
        noClasses().that().resideInAPackage("uy.ct.shortener.shortlink")
            .should().dependOnClassesThat().resideInAnyPackage("org.springframework.jdbc..", "java.sql..", "javax.sql..")
            .check(classes)
    }

    @Test
    fun `only the web adapter knows Spring Data, whose page size and sort it parses`() {
        noClasses().that().resideOutsideOfPackage("..internal.web..")
            .should().dependOnClassesThat().resideInAPackage("org.springframework.data..")
            .check(classes)
    }

    @Test
    fun `public api is free of the security framework`() {
        noClasses().that().resideInAPackage("uy.ct.shortener.shortlink")
            .should().dependOnClassesThat().resideInAPackage("org.springframework.security..")
            .check(classes)
    }

    @Test
    fun `nothing depends on the persistence adapter`() {
        noClasses().that().resideOutsideOfPackage("..internal.persistence..")
            .should().dependOnClassesThat().resideInAPackage("..internal.persistence..")
            .check(classes)
    }
}
