package uy.ct.shortener.tools

/**
 * A pseudo-random bijection of `[0, space)` onto itself, and the base62 text of its values.
 *
 * - [valueAt] maps the index `i` to a value so that no two indexes of the space share one. Any range of indexes can be
 *   generated by any thread, in any order, and no value repeats: no coordination, and no check for duplicates.
 * - It is a Feistel network of [ROUNDS] rounds over the smallest even number of bits that holds the space, with the cycle
 *   walk for what lands outside it: the network is applied again until the value is inside. A bijection of a larger set
 *   restricted this way is a bijection of the space, at about 1.25 rounds of the network per index for the 7 character space.
 * - The same [seed] and space give the same sequence. The values look random but are not secret: the round function is not a
 *   cipher, and nothing here should be used to pick codes that must not be guessed.
 * - With the space of the codes the application generates ([GENERATED_SPACE]) the first `n` indexes are `n` distinct codes, so
 *   a dataset of any size up to 62^7 is a prefix of the same sequence.
 */
class CodePermutation(seed: Long, private val space: Long = GENERATED_SPACE) {

    private val halfBits = (64 - java.lang.Long.numberOfLeadingZeros(space - 1) + 1) / 2
    private val halfMask = (1L shl halfBits) - 1
    private val keys = LongArray(ROUNDS)

    init {
        require(space >= 2) { "the space must hold at least 2 values, was $space" }
        require(halfBits <= 31) { "the space is too large: $space" }
        var state = seed
        for (round in keys.indices) {
            state += GOLDEN_GAMMA
            keys[round] = mix(state)
        }
    }

    fun valueAt(index: Long): Long {
        require(index in 0 until space) { "the index must be in [0, $space), was $index" }
        var value = index
        do {
            value = network(value)
        } while (value >= space)
        return value
    }

    private fun network(value: Long): Long {
        var left = value ushr halfBits
        var right = value and halfMask
        for (key in keys) {
            val next = left xor (mix(right xor key) and halfMask)
            left = right
            right = next
        }
        return (left shl halfBits) or right
    }

    companion object {
        const val ROUNDS = 6

        const val GENERATED_SPACE = 3_521_614_606_208L

        private const val GOLDEN_GAMMA = -0x61c8864680b583ebL

        private val MULTIPLIER_1 = 0xbf58476d1ce4e5b9UL.toLong()

        private val MULTIPLIER_2 = 0x94d049bb133111ebUL.toLong()

        private fun mix(value: Long): Long {
            var z = value
            z = (z xor (z ushr 30)) * MULTIPLIER_1
            z = (z xor (z ushr 27)) * MULTIPLIER_2
            return z xor (z ushr 31)
        }
    }
}

/**
 * Base62 with the alphabet of `ShortCode.ALPHABET` in the application, fixed at [LENGTH] characters, most significant first.
 * The application is not a dependency of the tools, so the alphabet is repeated here: `DatasetTest` pins it.
 */
object Base62 {
    const val ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

    const val LENGTH = 7

    private val BYTES = ALPHABET.toByteArray(Charsets.US_ASCII)

    fun encode(value: Long, into: ByteArray, offset: Int) {
        var rest = value
        for (position in offset + LENGTH - 1 downTo offset) {
            into[position] = BYTES[(rest % 62).toInt()]
            rest /= 62
        }
    }

    fun encode(value: Long): String = ByteArray(LENGTH).also { encode(value, it, 0) }.toString(Charsets.US_ASCII)

    fun decode(code: String): Long = code.fold(0L) { total, character -> total * 62 + ALPHABET.indexOf(character) }
}
