CREATE TABLE short_link
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code TEXT                     NOT NULL,
    target_url TEXT                     NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_short_link_short_code UNIQUE (short_code)
);
