apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortener
  labels:
    app.kubernetes.io/name: shortener
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shortener
                port:
                  name: http
